[package]
name = "img2xterm-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
png = { version = "0.17", features = [] }
# image = { version = "0.25" }
bytemuck = "1"
rgb = { version = "0.8", features = ["bytemuck"] }
